### PR TITLE
Various Improvements & Fixes

### LINKED ISSUE #32: Document source and license of graphics

### PR DESCRIPTION
**Pull request by yjf2002ghty**
#32 #62 

# After This Change
### Fog Of War

Added a dropdown to select fog of war mode, which applies to all variants. _**This is only a visual effect and does not change game logic.**_ The player is only able to see the squares that they can move to and squares that have their own pieces on in their turn. When it's opponent's turn, the player is only able to see their own pieces. Wall squares are always visible.

### UI Themes

Custom UI theme support. This loads CSS files from server into memory and apply them to the webpage to change the webpage content styles. Note that the browser needs to support AVIF format image to show the backgrounds of some themes.

### Move Visualization
Now clicking the moves in the PGN division and the principal variations division can show a mini board that displays the board position after making that move, if "Move Visualization" checkbox is checked. This is disabled by default because generating these elements costs more time than generating plain text.

### GUI
1. Made the evaluation value in PVs more noticeable.
2. Added missing variant settings.
3. Added tooltips for most inputs/buttons.
4. Improved board coordinate display style to make them more noticeable and not be covered by pocket.
5. Added a restart button which clears moves and set position to FEN.
6. Timing system is more accurate and added a highlight during time excess.
7. Added a start here button which allows to set current position to the position displayed on the board.
8. Better principal variation display.
9. Now the webpage will shorten the elements in the right panel and wrap elements in the top areas instead of scrolling sideward. 
10. Added a mini board to visualize the moves in move history and engine principal variations.
11. Added a dropdown to change board coordinate.
12. Added a <start here> button to allow users start playing at previously played positions.
13. Now ATAXX and similar variants that can drop pieces without having a pocket are supported. Solves #62 
14. Improved some slow functions.
15. Updated ChessgroundX version.
16. Supports fischer random.
17. Supports a simple engine match manager.

### Build & CI
1. Added compression and mangling for HTML and JS files to reduce their size.
2. Use 7ZIP-LZMA2 to upload artifacts which significantly reduces archive file size.
3. Improved CI & release maker process. Now they will provide a script version, and CI will upload the source code that the push or pull request uses.
4. The structure of this project has changed. See __*Fixes*__ chapter.
5. A script is added to custom the generations of the CSS of chessground board size, generic board styles, and letters theme, and the SVG of generic boards.

### Vercel Online
Added caching policy for Vercel. This will reduce the loading time of the page and network flow.

### Documentation
1. Added attribution in COPYING.md. If there is no problem, Document source and license of graphics #32 can be closed.
2. Added a README for `src` folder which explains the files in it.

## Fixes
1. Fixed unexpected null move input when in review mode.
2. Fixed half move display in "Half Move Number" dialog.
3. Fixed PV display when reducing PV count without stopping engine thinking.
4. Fixed some style issues.
6. Fixed `getFileFromServer` not working in new browsers.
7. Fixed check square highlight. Now checked pieces can be displayed correctly if there are multiple ones.
8. Fixed board editor does not show the newly added pieces in pocket when adding piece to pocket.
9. _**[Critical]**_ Fixed page loading issue, when Fairy-Stockfish is loaded before variant settings, position variants and themes. Now the dropdowns can be loaded correctly in this case.
10. _**[Critical]**_ Fixed "Play against Fairy-Stockfish" page loading issue of fairy-stockfish.wasm on latest Firefox. This changes the source structure. All HTML files are moved to `src/html/` and all JS files are moved to `src/js/`. A script that is used to make `index.html` is created.

### CODE REVIEW

**Comment by yjf2002ghty** [comment]
> @yjf2002ghty is attempting to deploy a commit to the **ianfab's projects** Team on [Vercel](https://vercel.com).
> 
> A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=ianfab's%20projects&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%221361f9516478c153bd40a2aa6687c08575fa2152%22%7D%2C%22id%22%3A%22QmeYyyyDG1TtfudcvanqvwcLY31Dihm6XadHoZBEuockNP%22%2C%22org%22%3A%22ianfab%22%2C%22prId%22%3A83%2C%22repo%22%3A%22fairyground%22%7D).

Due to the introduction of custom UI themes, some bitmap images (in JPEG format) are used, which can consume network flow if the caching policy is not set. This change intends to add the cache control for all JPG files so browsers can cache the JPG files for a day before requesting them from server and thus reduce the network flow.

If you think this is problematic, I can revert the changes to dark mode support.

Below are some screenshots of the custom UI theme feature:
image
image
image

**Comment by ianfab** [comment]
Thanks and sorry for the delay. Will have a look in the next days.

**Comment by ianfab** [comment]
Thanks a lot, that is a huge number of improvements.

By the way, if you feel like changing changing something regarding the normal vs advanced page, I am more open to merging/changing them now. With more and more features being added the difference between the two pages kind of gets smaller, so I am no longer sure whether it is worth having them separated right now.

**Comment by yjf2002ghty** [comment]
In my opinion, since the advanced page displays a lot of aspects that do not focus on playing against Fairy-Stockfish (board setup, analysis, etc.), and has a complicated state handling, the play page should remain its initial purpose that users can play a game within a few clicks without being distracted by other elements not related to playing. So I prefer to keep this page.

The build process is intended to reduce development overhead as it reuses `advanced.html` and hides unnecessary elements thus having no need to commit changes to 2 different pages. However on recent Firefox the previous `iframe` implementation is having problems, so I changed the implementation of `index.html`.

**Pull request merged**
